### PR TITLE
Use `remote-git-tags` instead of GitHub API

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/sindresorhus/remote-git-tags

Resolves https://github.com/ember-cli/ember-try/issues/112 and https://github.com/ember-cli/ember-try-config/pull/9#issuecomment-339972650

### CODE REVIEW

**Comment by rwjblue** [comment]
Two concerns:

1. From the README I’d remote-git-tags:

> I'm using this successfully against GitHub repos, but the underlaying modules are not that actively maintained, so I wouldn't recommend using this for production critical code.

2. Doesn’t github also rate limit access to the git:// remotes by IP?

**Comment by Turbo87** [comment]
> Doesn’t github also rate limit access to the git:// remotes by IP?

not that I'm aware of, haven't found any information on that. and if it did then services like TravisCI wouldn't work well since they need to clone thousands of projects every minute/second/whatever.

> I'm using this successfully against GitHub repos, but the underlaying modules are not that actively maintained, so I wouldn't recommend using this for production critical code.

yeah, I read that too, but if something breaks we can probably just fork and provide a fixed version. in any case this solution seems easier and less brittle than what we currently have and doesn't require an extra deploy step for Ember.js.

**Comment by rwjblue** [comment]
Seems good to me. Thanks for putting this together!

**Comment by rwjblue** [comment]
@kategengler - Any objections?

**Comment by kategengler** [comment]
Nope, looks good to me though I'd still like to explore a `npm info` solution.

**Pull request merged**
